FLAGS = [
    {"country": "Andorra", "image_url": "001.png"},
    {"country": "United Arab Emirates", "image_url": "002.png"},
    {"country": "Afghanistan", "image_url": "003.png"},
    {"country": "Antigua and Barbuda", "image_url": "004.png"},
    {"country": "Anguilla", "image_url": "005.png"},
    {"country": "Albania", "image_url": "006.png"},
    {"country": "Armenia", "image_url": "007.png"},
    {"country": "Angola", "image_url": "008.png"},
    {"country": "Antarctica", "image_url": "009.png"},
    {"country": "Argentina", "image_url": "010.png"},
    {"country": "American Samoa", "image_url": "011.png"},
    {"country": "Austria", "image_url": "012.png"},
    {"country": "Australia", "image_url": "013.png"},
    {"country": "Aruba", "image_url": "014.png"},
    {"country": "Åland Islands", "image_url": "015.png"},
    {"country": "Azerbaijan", "image_url": "016.png"},
    {"country": "Bosnia and Herzegovina", "image_url": "017.png"},
    {"country": "Barbados", "image_url": "018.png"},
    {"country": "Bangladesh", "image_url": "019.png"},
    {"country": "Belgium", "image_url": "020.png"},
    {"country": "Burkina Faso", "image_url": "021.png"},
    {"country": "Bulgaria", "image_url": "022.png"},
    {"country": "Bahrain", "image_url": "023.png"},
    {"country": "Burundi", "image_url": "024.png"},
    {"country": "Benin", "image_url": "025.png"},
    {"country": "Bermuda", "image_url": "027.png"},
    {"country": "Brunei", "image_url": "028.png"},
    {"country": "Bolivia", "image_url": "029.png"},
    {"country": "Bonaire, Sint Eustatius and Saba", "image_url": "030.png"},
    {"country": "Brazil", "image_url": "031.png"},
    {"country": "Bahamas", "image_url": "032.png"},
    {"country": "Bhutan", "image_url": "033.png"},
    {"country": "Botswana", "image_url": "035.png"},
    {"country": "Belarus", "image_url": "036.png"},
    {"country": "Belize", "image_url": "037.png"},
    {"country": "Canada", "image_url": "038.png"},
    {"country": "Cocos (Keeling) Islands", "image_url": "039.png"},
    {"country": "Democratic Republic of the Congo", "image_url": "040.png"},
    {"country": "Central African Republic", "image_url": "041.png"},
    {"country": "Republic of the Congo", "image_url": "042.png"},
    {"country": "Switzerland", "image_url": "043.png"},
    {"country": "Côte d'Ivoire", "image_url": "044.png"},
    {"country": "Cook Islands", "image_url": "045.png"},
    {"country": "Chile", "image_url": "046.png"},
    {"country": "Cameroon", "image_url": "047.png"},
    {"country": "China", "image_url": "048.png"},
    {"country": "Colombia", "image_url": "049.png"},
    {"country": "Costa Rica", "image_url": "050.png"},
    {"country": "Cuba", "image_url": "051.png"},
    {"country": "Cape Verde", "image_url": "052.png"},
    {"country": "Curaçao", "image_url": "053.png"},
    {"country": "Christmas Island", "image_url": "054.png"},
    {"country": "Cyprus", "image_url": "055.png"},
    {"country": "Czechia", "image_url": "056.png"},
    {"country": "Germany", "image_url": "057.png"},
    {"country": "Djibouti", "image_url": "058.png"},
    {"country": "Denmark", "image_url": "059.png"},
    {"country": "Dominica", "image_url": "060.png"},
    {"country": "Dominican Republic", "image_url": "061.png"},
    {"country": "Algeria", "image_url": "062.png"},
    {"country": "Ecuador", "image_url": "063.png"},
    {"country": "Estonia", "image_url": "064.png"},
    {"country": "Egypt", "image_url": "065.png"},
    {"country": "Western Sahara", "image_url": "066.png"},
    {"country": "Eritrea", "image_url": "067.png"},
    {"country": "Spain", "image_url": "068.png"},
    {"country": "Ethiopia", "image_url": "069.png"},
    {"country": "Finland", "image_url": "070.png"},
    {"country": "Fiji", "image_url": "071.png"},
    {"country": "Falkland Islands", "image_url": "072.png"},
    {"country": "Micronesia", "image_url": "073.png"},
    {"country": "Faroe Islands", "image_url": "074.png"},
    {"country": "France", "image_url": "075.png"},
    {"country": "Gabon", "image_url": "076.png"},
    {"country": "England", "image_url": "077.png"},
    {"country": "Northern Ireland", "image_url": "078.png"},
    {"country": "Scotland", "image_url": "079.png"},
    {"country": "Wales", "image_url": "080.png"},
    {"country": "United Kingdom", "image_url": "081.png"},
    {"country": "Grenada", "image_url": "082.png"},
    {"country": "Georgia", "image_url": "083.png"},
    {"country": "French Guiana", "image_url": "084.png"},
    {"country": "Guernsey", "image_url": "085.png"},
    {"country": "Ghana", "image_url": "086.png"},
    {"country": "Gibraltar", "image_url": "087.png"},
    {"country": "Greenland", "image_url": "088.png"},
    {"country": "Gambia", "image_url": "089.png"},
    {"country": "Guinea", "image_url": "090.png"},
    {"country": "Equatorial Guinea", "image_url": "092.png"},
    {"country": "Greece", "image_url": "093.png"},
    {"country": "South Georgia and the South Sandwich Islands", "image_url": "094.png"},
    {"country": "Guatemala", "image_url": "095.png"},
    {"country": "Guam", "image_url": "096.png"},
    {"country": "Guinea-Bissau", "image_url": "097.png"},
    {"country": "Guyana", "image_url": "098.png"},
    {"country": "Hong Kong", "image_url": "099.png"},
    {"country": "Honduras", "image_url": "101.png"},
    {"country": "Croatia", "image_url": "102.png"},
    {"country": "Haiti", "image_url": "103.png"},
    {"country": "Hungary", "image_url": "104.png"},
    {"country": "Indonesia", "image_url": "105.png"},
    {"country": "Ireland", "image_url": "106.png"},
    {"country": "Israel", "image_url": "107.png"},
    {"country": "Isle of Man", "image_url": "108.png"},
    {"country": "India", "image_url": "109.png"},
    {"country": "British Indian Ocean Territory", "image_url": "110.png"},
    {"country": "Iraq", "image_url": "111.png"},
    {"country": "Iran", "image_url": "112.png"},
    {"country": "Iceland", "image_url": "113.png"},
    {"country": "Italy", "image_url": "114.png"},
    {"country": "Jersey", "image_url": "115.png"},
    {"country": "Jamaica", "image_url": "116.png"},
    {"country": "Jordan", "image_url": "117.png"},
    {"country": "Japan", "image_url": "118.png"},
    {"country": "Kenya", "image_url": "119.png"},
    {"country": "Kyrgyzstan", "image_url": "120.png"},
    {"country": "Cambodia", "image_url": "121.png"},
    {"country": "Kiribati", "image_url": "122.png"},
    {"country": "Comoros", "image_url": "123.png"},
    {"country": "Saint Kitts and Nevis", "image_url": "124.png"},
    {"country": "North Korea", "image_url": "125.png"},
    {"country": "South Korea", "image_url": "126.png"},
    {"country": "Kuwait", "image_url": "127.png"},
    {"country": "Cayman Islands", "image_url": "128.png"},
    {"country": "Kazakhstan", "image_url": "129.png"},
    {"country": "Laos", "image_url": "130.png"},
    {"country": "Lebanon", "image_url": "131.png"},
    {"country": "Saint Lucia", "image_url": "132.png"},
    {"country": "Liechtenstein", "image_url": "133.png"},
    {"country": "Sri Lanka", "image_url": "134.png"},
    {"country": "Liberia", "image_url": "135.png"},
    {"country": "Lesotho", "image_url": "136.png"},
    {"country": "Lithuania", "image_url": "137.png"},
    {"country": "Luxembourg", "image_url": "138.png"},
    {"country": "Latvia", "image_url": "139.png"},
    {"country": "Libya", "image_url": "140.png"},
    {"country": "Morocco", "image_url": "141.png"},
    {"country": "Monaco", "image_url": "142.png"},
    {"country": "Moldova, Republic of", "image_url": "143.png"},
    {"country": "Montenegro", "image_url": "144.png"},
    {"country": "Madagascar", "image_url": "146.png"},
    {"country": "Marshall Islands", "image_url": "147.png"},
    {"country": "North Macedonia", "image_url": "148.png"},
    {"country": "Mali", "image_url": "149.png"},
    {"country": "Myanmar", "image_url": "150.png"},
    {"country": "Mongolia", "image_url": "151.png"},
    {"country": "Macao", "image_url": "152.png"},
    {"country": "Northern Mariana Islands", "image_url": "153.png"},
    {"country": "Mauritania", "image_url": "155.png"},
    {"country": "Montserrat", "image_url": "156.png"},
    {"country": "Malta", "image_url": "157.png"},
    {"country": "Mauritius", "image_url": "158.png"},
    {"country": "Maldives", "image_url": "159.png"},
    {"country": "Malawi", "image_url": "160.png"},
    {"country": "Mexico", "image_url": "161.png"},
    {"country": "Malaysia", "image_url": "162.png"},
    {"country": "Mozambique", "image_url": "163.png"},
    {"country": "Namibia", "image_url": "164.png"},
    {"country": "New Caledonia", "image_url": "165.png"},
    {"country": "Niger", "image_url": "166.png"},
    {"country": "Norfolk Island", "image_url": "167.png"},
    {"country": "Nigeria", "image_url": "168.png"},
    {"country": "Nicaragua", "image_url": "169.png"},
    {"country": "Netherlands", "image_url": "170.png"},
    {"country": "Norway", "image_url": "171.png"},
    {"country": "Nepal", "image_url": "172.png"},
    {"country": "Nauru", "image_url": "173.png"},
    {"country": "Niue", "image_url": "174.png"},
    {"country": "New Zealand", "image_url": "175.png"},
    {"country": "Oman", "image_url": "176.png"},
    {"country": "Panama", "image_url": "177.png"},
    {"country": "Peru", "image_url": "178.png"},
    {"country": "French Polynesia", "image_url": "179.png"},
    {"country": "Papua New Guinea", "image_url": "180.png"},
    {"country": "Philippines", "image_url": "181.png"},
    {"country": "Pakistan", "image_url": "182.png"},
    {"country": "Poland", "image_url": "183.png"},
    {"country": "Pitcairn", "image_url": "185.png"},
    {"country": "Puerto Rico", "image_url": "186.png"},
    {"country": "Palestine", "image_url": "187.png"},
    {"country": "Portugal", "image_url": "188.png"},
    {"country": "Palau", "image_url": "189.png"},
    {"country": "Paraguay", "image_url": "190.png"},
    {"country": "Qatar", "image_url": "191.png"},
    {"country": "Romania", "image_url": "193.png"},
    {"country": "Serbia", "image_url": "194.png"},
    {"country": "Russia", "image_url": "195.png"},
    {"country": "Rwanda", "image_url": "196.png"},
    {"country": "Saudi Arabia", "image_url": "197.png"},
    {"country": "Solomon Islands", "image_url": "198.png"},
    {"country": "Seychelles", "image_url": "199.png"},
    {"country": "Sudan", "image_url": "200.png"},
    {"country": "Sweden", "image_url": "201.png"},
    {"country": "Singapore", "image_url": "202.png"},
    {"country": "Saint Helena", "image_url": "203.png"},
    {"country": "Slovenia", "image_url": "204.png"},
    {"country": "Slovakia", "image_url": "206.png"},
    {"country": "Sierra Leone", "image_url": "207.png"},
    {"country": "San Marino", "image_url": "208.png"},
    {"country": "Senegal", "image_url": "209.png"},
    {"country": "Somalia", "image_url": "210.png"},
    {"country": "Suriname", "image_url": "211.png"},
    {"country": "South Sudan", "image_url": "212.png"},
    {"country": "Sao Tome and Principe", "image_url": "213.png"},
    {"country": "El Salvador", "image_url": "214.png"},
    {"country": "Sint Maarten", "image_url": "215.png"},
    {"country": "Syria", "image_url": "216.png"},
    {"country": "Eswatini", "image_url": "217.png"},
    {"country": "Turks and Caicos Islands", "image_url": "218.png"},
    {"country": "Chad", "image_url": "219.png"},
    {"country": "French Southern Territories", "image_url": "220.png"},
    {"country": "Togo", "image_url": "221.png"},
    {"country": "Thailand", "image_url": "222.png"},
    {"country": "Tajikistan", "image_url": "223.png"},
    {"country": "Tokelau", "image_url": "224.png"},
    {"country": "Timor-Leste", "image_url": "225.png"},
    {"country": "Turkmenistan", "image_url": "226.png"},
    {"country": "Tunisia", "image_url": "227.png"},
    {"country": "Tonga", "image_url": "228.png"},
    {"country": "Turkey", "image_url": "229.png"},
    {"country": "Trinidad and Tobago", "image_url": "230.png"},
    {"country": "Tuvalu", "image_url": "231.png"},
    {"country": "Taiwan", "image_url": "232.png"},
    {"country": "Tanzania", "image_url": "233.png"},
    {"country": "Ukraine", "image_url": "234.png"},
    {"country": "Uganda", "image_url": "235.png"},
    {"country": "United States of America", "image_url": "237.png"},
    {"country": "Uruguay", "image_url": "238.png"},
    {"country": "Uzbekistan", "image_url": "239.png"},
    {"country": "Vatican", "image_url": "240.png"},
    {"country": "Saint Vincent and the Grenadines", "image_url": "241.png"},
    {"country": "Venezuela", "image_url": "242.png"},
    {"country": "British Virgin Islands", "image_url": "243.png"},
    {"country": "U.S. Virgin Islands", "image_url": "244.png"},
    {"country": "Vietnam", "image_url": "245.png"},
    {"country": "Vanuatu", "image_url": "246.png"},
    {"country": "Samoa", "image_url": "248.png"},
    {"country": "Kosovo", "image_url": "249.png"},
    {"country": "Yemen", "image_url": "250.png"},
    {"country": "South Africa", "image_url": "252.png"},
    {"country": "Zambia", "image_url": "253.png"},
    {"country": "Zimbabwe", "image_url": "254.png"}
]