FLAGS = [
    {"country": "Andorra", "image_url": "ad.png"},
    {"country": "United Arab Emirates", "image_url": "ae.png"},
    {"country": "Afghanistan", "image_url": "af.png"},
    {"country": "Antigua and Barbuda", "image_url": "ag.png"},
    {"country": "Anguilla", "image_url": "ai.png"},
    {"country": "Albania", "image_url": "al.png"},
    {"country": "Armenia", "image_url": "am.png"},
    {"country": "Angola", "image_url": "ao.png"},
    {"country": "Antarctica", "image_url": "aq.png"},
    {"country": "Argentina", "image_url": "ar.png"},
    {"country": "American Samoa", "image_url": "as.png"},
    {"country": "Austria", "image_url": "at.png"},
    {"country": "Australia", "image_url": "au.png"},
    {"country": "Aruba", "image_url": "aw.png"},
    {"country": "Åland Islands", "image_url": "ax.png"},
    {"country": "Azerbaijan", "image_url": "az.png"},
    {"country": "Bosnia and Herzegovina", "image_url": "ba.png"},
    {"country": "Barbados", "image_url": "bb.png"},
    {"country": "Bangladesh", "image_url": "bd.png"},
    {"country": "Belgium", "image_url": "be.png"},
    {"country": "Burkina Faso", "image_url": "bf.png"},
    {"country": "Bulgaria", "image_url": "bg.png"},
    {"country": "Bahrain", "image_url": "bh.png"},
    {"country": "Burundi", "image_url": "bi.png"},
    {"country": "Benin", "image_url": "bj.png"},
    {"country": "Saint Barthélemy", "image_url": "bl.png"},
    {"country": "Bermuda", "image_url": "bm.png"},
    {"country": "Brunei Darussalam", "image_url": "bn.png"},
    {"country": "Bolivia, Plurinational State of", "image_url": "bo.png"},
    {"country": "Bonaire, Sint Eustatius and Saba", "image_url": "bq.png"},
    {"country": "Brazil", "image_url": "br.png"},
    {"country": "Bahamas", "image_url": "bs.png"},
    {"country": "Bhutan", "image_url": "bt.png"},
    {"country": "Bouvet Island", "image_url": "bv.png"},
    {"country": "Botswana", "image_url": "bw.png"},
    {"country": "Belarus", "image_url": "by.png"},
    {"country": "Belize", "image_url": "bz.png"},
    {"country": "Canada", "image_url": "ca.png"},
    {"country": "Cocos (Keeling) Islands", "image_url": "cc.png"},
    {"country": "Congo, Democratic Republic of the", "image_url": "cd.png"},
    {"country": "Central African Republic", "image_url": "cf.png"},
    {"country": "Congo", "image_url": "cg.png"},
    {"country": "Switzerland", "image_url": "ch.png"},
    {"country": "Côte d'Ivoire", "image_url": "ci.png"},
    {"country": "Cook Islands", "image_url": "ck.png"},
    {"country": "Chile", "image_url": "cl.png"},
    {"country": "Cameroon", "image_url": "cm.png"},
    {"country": "China", "image_url": "cn.png"},
    {"country": "Colombia", "image_url": "co.png"},
    {"country": "Costa Rica", "image_url": "cr.png"},
    {"country": "Cuba", "image_url": "cu.png"},
    {"country": "Cape Verde", "image_url": "cv.png"},
    {"country": "Curaçao", "image_url": "cw.png"},
    {"country": "Christmas Island", "image_url": "cx.png"},
    {"country": "Cyprus", "image_url": "cy.png"},
    {"country": "Czechia", "image_url": "cz.png"},
    {"country": "Germany", "image_url": "de.png"},
    {"country": "Djibouti", "image_url": "dj.png"},
    {"country": "Denmark", "image_url": "dk.png"},
    {"country": "Dominica", "image_url": "dm.png"},
    {"country": "Dominican Republic", "image_url": "do.png"},
    {"country": "Algeria", "image_url": "dz.png"},
    {"country": "Ecuador", "image_url": "ec.png"},
    {"country": "Estonia", "image_url": "ee.png"},
    {"country": "Egypt", "image_url": "eg.png"},
    {"country": "Western Sahara", "image_url": "eh.png"},
    {"country": "Eritrea", "image_url": "er.png"},
    {"country": "Spain", "image_url": "es.png"},
    {"country": "Ethiopia", "image_url": "et.png"},
    {"country": "Finland", "image_url": "fi.png"},
    {"country": "Fiji", "image_url": "fj.png"},
    {"country": "Falkland Islands (Malvinas)", "image_url": "fk.png"},
    {"country": "Micronesia, Federated States of", "image_url": "fm.png"},
    {"country": "Faroe Islands", "image_url": "fo.png"},
    {"country": "France", "image_url": "fr.png"},
    {"country": "Gabon", "image_url": "ga.png"},
    {"country": "United Kingdom of Great Britain and Northern Ireland", "image_url": "gb-eng.png"},
    {"country": "Northern Ireland", "image_url": "gb-nir.png"},
    {"country": "Scotland", "image_url": "gb-sct.png"},
    {"country": "Wales", "image_url": "gb-wls.png"},
    {"country": "United Kingdom", "image_url": "gb.png"},
    {"country": "Grenada", "image_url": "gd.png"},
    {"country": "Georgia", "image_url": "ge.png"},
    {"country": "French Guiana", "image_url": "gf.png"},
    {"country": "Guernsey", "image_url": "gg.png"},
    {"country": "Ghana", "image_url": "gh.png"},
    {"country": "Gibraltar", "image_url": "gi.png"},
    {"country": "Greenland", "image_url": "gl.png"},
    {"country": "Gambia", "image_url": "gm.png"},
    {"country": "Guinea", "image_url": "gn.png"},
    {"country": "Guadeloupe", "image_url": "gp.png"},
    {"country": "Equatorial Guinea", "image_url": "gq.png"},
    {"country": "Greece", "image_url": "gr.png"},
    {"country": "South Georgia and the South Sandwich Islands", "image_url": "gs.png"},
    {"country": "Guatemala", "image_url": "gt.png"},
    {"country": "Guam", "image_url": "gu.png"},
    {"country": "Guinea-Bissau", "image_url": "gw.png"},
    {"country": "Guyana", "image_url": "gy.png"},
    {"country": "Hong Kong", "image_url": "hk.png"},
    {"country": "Heard Island and McDonald Islands", "image_url": "hm.png"},
    {"country": "Honduras", "image_url": "hn.png"},
    {"country": "Croatia", "image_url": "hr.png"},
    {"country": "Haiti", "image_url": "ht.png"},
    {"country": "Hungary", "image_url": "hu.png"},
    {"country": "Indonesia", "image_url": "id.png"},
    {"country": "Ireland", "image_url": "ie.png"},
    {"country": "Israel", "image_url": "il.png"},
    {"country": "Isle of Man", "image_url": "im.png"},
    {"country": "India", "image_url": "in.png"},
    {"country": "British Indian Ocean Territory", "image_url": "io.png"},
    {"country": "Iraq", "image_url": "iq.png"},
    {"country": "Iran, Islamic Republic of", "image_url": "ir.png"},
    {"country": "Iceland", "image_url": "is.png"},
    {"country": "Italy", "image_url": "it.png"},
    {"country": "Jersey", "image_url": "je.png"},
    {"country": "Jamaica", "image_url": "jm.png"},
    {"country": "Jordan", "image_url": "jo.png"},
    {"country": "Japan", "image_url": "jp.png"},
    {"country": "Kenya", "image_url": "ke.png"},
    {"country": "Kyrgyzstan", "image_url": "kg.png"},
    {"country": "Cambodia", "image_url": "kh.png"},
    {"country": "Kiribati", "image_url": "ki.png"},
    {"country": "Comoros", "image_url": "km.png"},
    {"country": "Saint Kitts and Nevis", "image_url": "kn.png"},
    {"country": "Korea, Democratic People's Republic of", "image_url": "kp.png"},
    {"country": "Korea, Republic of", "image_url": "kr.png"},
    {"country": "Kuwait", "image_url": "kw.png"},
    {"country": "Cayman Islands", "image_url": "ky.png"},
    {"country": "Kazakhstan", "image_url": "kz.png"},
    {"country": "Lao People's Democratic Republic", "image_url": "la.png"},
    {"country": "Lebanon", "image_url": "lb.png"},
    {"country": "Saint Lucia", "image_url": "lc.png"},
    {"country": "Liechtenstein", "image_url": "li.png"},
    {"country": "Sri Lanka", "image_url": "lk.png"},
    {"country": "Liberia", "image_url": "lr.png"},
    {"country": "Lesotho", "image_url": "ls.png"},
    {"country": "Lithuania", "image_url": "lt.png"},
    {"country": "Luxembourg", "image_url": "lu.png"},
    {"country": "Latvia", "image_url": "lv.png"},
    {"country": "Libya", "image_url": "ly.png"},
    {"country": "Morocco", "image_url": "ma.png"},
    {"country": "Monaco", "image_url": "mc.png"},
    {"country": "Moldova, Republic of", "image_url": "md.png"},
    {"country": "Montenegro", "image_url": "me.png"},
    {"country": "Saint Martin (French part)", "image_url": "mf.png"},
    {"country": "Madagascar", "image_url": "mg.png"},
    {"country": "Marshall Islands", "image_url": "mh.png"},
    {"country": "North Macedonia", "image_url": "mk.png"},
    {"country": "Mali", "image_url": "ml.png"},
    {"country": "Myanmar", "image_url": "mm.png"},
    {"country": "Mongolia", "image_url": "mn.png"},
    {"country": "Macao", "image_url": "mo.png"},
    {"country": "Northern Mariana Islands", "image_url": "mp.png"},
    {"country": "Martinique", "image_url": "mq.png"},
    {"country": "Mauritania", "image_url": "mr.png"},
    {"country": "Montserrat", "image_url": "ms.png"},
    {"country": "Malta", "image_url": "mt.png"},
    {"country": "Mauritius", "image_url": "mu.png"},
    {"country": "Maldives", "image_url": "mv.png"},
    {"country": "Malawi", "image_url": "mw.png"},
    {"country": "Mexico", "image_url": "mx.png"},
    {"country": "Malaysia", "image_url": "my.png"},
    {"country": "Mozambique", "image_url": "mz.png"},
    {"country": "Namibia", "image_url": "na.png"},
    {"country": "New Caledonia", "image_url": "nc.png"},
    {"country": "Niger", "image_url": "ne.png"},
    {"country": "Norfolk Island", "image_url": "nf.png"},
    {"country": "Nigeria", "image_url": "ng.png"},
    {"country": "Nicaragua", "image_url": "ni.png"},
    {"country": "Netherlands", "image_url": "nl.png"},
    {"country": "Norway", "image_url": "no.png"},
    {"country": "Nepal", "image_url": "np.png"},
    {"country": "Nauru", "image_url": "nr.png"},
    {"country": "Niue", "image_url": "nu.png"},
    {"country": "New Zealand", "image_url": "nz.png"},
    {"country": "Oman", "image_url": "om.png"},
    {"country": "Panama", "image_url": "pa.png"},
    {"country": "Peru", "image_url": "pe.png"},
    {"country": "French Polynesia", "image_url": "pf.png"},
    {"country": "Papua New Guinea", "image_url": "pg.png"},
    {"country": "Philippines", "image_url": "ph.png"},
    {"country": "Pakistan", "image_url": "pk.png"},
    {"country": "Poland", "image_url": "pl.png"},
    {"country": "Saint Pierre and Miquelon", "image_url": "pm.png"},
    {"country": "Pitcairn", "image_url": "pn.png"},
    {"country": "Puerto Rico", "image_url": "pr.png"},
    {"country": "Palestine, State of", "image_url": "ps.png"},
    {"country": "Portugal", "image_url": "pt.png"},
    {"country": "Palau", "image_url": "pw.png"},
    {"country": "Paraguay", "image_url": "py.png"},
    {"country": "Qatar", "image_url": "qa.png"},
    {"country": "Réunion", "image_url": "re.png"},
    {"country": "Romania", "image_url": "ro.png"},
    {"country": "Serbia", "image_url": "rs.png"},
    {"country": "Russian Federation", "image_url": "ru.png"},
    {"country": "Rwanda", "image_url": "rw.png"},
    {"country": "Saudi Arabia", "image_url": "sa.png"},
    {"country": "Solomon Islands", "image_url": "sb.png"},
    {"country": "Seychelles", "image_url": "sc.png"},
    {"country": "Sudan", "image_url": "sd.png"},
    {"country": "Sweden", "image_url": "se.png"},
    {"country": "Singapore", "image_url": "sg.png"},
    {"country": "Saint Helena, Ascension and Tristan da Cunha", "image_url": "sh.png"},
    {"country": "Slovenia", "image_url": "si.png"},
    {"country": "Svalbard and Jan Mayen", "image_url": "sj.png"},
    {"country": "Slovakia", "image_url": "sk.png"},
    {"country": "Sierra Leone", "image_url": "sl.png"},
    {"country": "San Marino", "image_url": "sm.png"},
    {"country": "Senegal", "image_url": "sn.png"},
    {"country": "Somalia", "image_url": "so.png"},
    {"country": "Suriname", "image_url": "sr.png"},
    {"country": "South Sudan", "image_url": "ss.png"},
    {"country": "Sao Tome and Principe", "image_url": "st.png"},
    {"country": "El Salvador", "image_url": "sv.png"},
    {"country": "Sint Maarten (Dutch part)", "image_url": "sx.png"},
    {"country": "Syrian Arab Republic", "image_url": "sy.png"},
    {"country": "Eswatini", "image_url": "sz.png"},
    {"country": "Turks and Caicos Islands", "image_url": "tc.png"},
    {"country": "Chad", "image_url": "td.png"},
    {"country": "French Southern Territories", "image_url": "tf.png"},
    {"country": "Togo", "image_url": "tg.png"},
    {"country": "Thailand", "image_url": "th.png"},
    {"country": "Tajikistan", "image_url": "tj.png"},
    {"country": "Tokelau", "image_url": "tk.png"},
    {"country": "Timor-Leste", "image_url": "tl.png"},
    {"country": "Turkmenistan", "image_url": "tm.png"},
    {"country": "Tunisia", "image_url": "tn.png"},
    {"country": "Tonga", "image_url": "to.png"},
    {"country": "Turkey", "image_url": "tr.png"},
    {"country": "Trinidad and Tobago", "image_url": "tt.png"},
    {"country": "Tuvalu", "image_url": "tv.png"},
    {"country": "Taiwan, Province of China", "image_url": "tw.png"},
    {"country": "Tanzania, United Republic of", "image_url": "tz.png"},
    {"country": "Ukraine", "image_url": "ua.png"},
    {"country": "Uganda", "image_url": "ug.png"},
    {"country": "United States Minor Outlying Islands", "image_url": "um.png"},
    {"country": "United States of America", "image_url": "us.png"},
    {"country": "Uruguay", "image_url": "uy.png"},
    {"country": "Uzbekistan", "image_url": "uz.png"},
    {"country": "Holy See", "image_url": "va.png"},
    {"country": "Saint Vincent and the Grenadines", "image_url": "vc.png"},
    {"country": "Venezuela, Bolivarian Republic of", "image_url": "ve.png"},
    {"country": "Virgin Islands, British", "image_url": "vg.png"},
    {"country": "Virgin Islands, U.S.", "image_url": "vi.png"},
    {"country": "Viet Nam", "image_url": "vn.png"},
    {"country": "Vanuatu", "image_url": "vu.png"},
    {"country": "Wallis and Futuna", "image_url": "wf.png"},
    {"country": "Samoa", "image_url": "ws.png"},
    {"country": "Yemen", "image_url": "ye.png"},
    {"country": "Mayotte", "image_url": "yt.png"},
    {"country": "South Africa", "image_url": "za.png"},
    {"country": "Zambia", "image_url": "zm.png"},
    {"country": "Zimbabwe", "image_url": "zw.png"}
]